[http]
cg = 7
overallUrl = "https://rallysimfans.hu/rbr/csv_export_results.php?rally_id=%d&cg=%d"
betaUrl = "https://rallysimfans.hu/rbr/csv_export_beta.php?rally_id=%d"
[general]
points = [32, 28, 25, 22, 20, 18, 16, 14, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
headers = "pos,driver,points"

[database]
name = "octanepoints.db"