[general]
points = [32, 28, 25, 22, 20, 18, 16, 14, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
classPoints = [32, 28, 25, 22, 20, 18, 16, 14, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
classesType = "driver" # Options: "car", "driver"
descriptionDir = "rallies"

[database]
name = "octanepoints.db"

[[classes]]
name = "Gold"
description = "Gold Class Drivers"
categories = []
drivers = ["Taxi615", "BenjaminTheBean", "Voksy", "Horizontos", "Shotgun Willie", "polypunkki", "Slow_Tibi", "Morgan P", "fafar", "Isshy_Wondertwin"]

[[classes]]
name = "Silver"
description = "Silver Class Drivers"
categories = []
drivers = ["Hairless_Bear", "oka22", "Best2nd", "S_Triper", "Wreckles", "adamcul1", "gamermadness960", "egor_truex", "Atomic Frawgg", "GriffGriff"]